### ISSUE TITLE
metrics-ldap.rb Error Cannot connect to 

### ISSUE THREAD

**Issue by roumano** [sensu-plugins/sensu-plugins-openldap#3]
I have a issue with the metrics-ldap.rb with my rub version ( 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux])
i always have a error "Cannot connect to ..." but the error message it's not true :  

after investigating on it, it's a issue with the variable **message** ( line 101 ) 
for me, it's not initialized before so the **+=**  doesn't work

to fix it, replace 
```
message += 'So far' 
```
to
```
message = 'So far'
```
is working
and it's also working to add message = '' before the +=

**Comment by majormoses** [comment]
@roumano would you be willing to put togethor a pr for this?

**Comment by majormoses** [comment]
closed per: https://github.com/sensu-plugins/sensu-plugins-openldap/pull/5
